/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import javax.swing.JOptionPane;
import model.MySQL;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author user
 */
public class login extends javax.swing.JFrame {

    public login() {
        initComponents();
    }

    // Chain of Responsibility Pattern
    abstract class AuthHandler {

        private AuthHandler nextHandler;

        public AuthHandler setNext(AuthHandler nextHandler) {
            this.nextHandler = nextHandler;
            return nextHandler;
        }

        public void handle(String username, String password) {
            if (check(username, password)) {
                if (nextHandler != null) {
                    nextHandler.handle(username, password);
                } else {
                    System.out.println(" Authentication successful!");
                }
            } else {
                System.out.println("Authentication failed!");
            }
        }

        protected abstract boolean check(String username, String password);
    }

// Concrete Handler 1: Username validation
    class UsernameHandler extends AuthHandler {

        @Override
        protected boolean check(String username, String password) {
            if (username == null || username.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Username cannot be empty");
                return false;
            }
            return true;
        }
    }

// Concrete Handler 2: Password validation
    class PasswordHandler extends AuthHandler {

        @Override
        protected boolean check(String username, String password) {
            if (password == null || password.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Password cannot be empty");
                return false;
            }
            return true;
        }
    }

// Concrete Handler 3: Credential check
    class CredentialHandler extends AuthHandler {

        private final Map<String, String[]> users = new HashMap<>();

        public CredentialHandler() {
            // Static username, password, role 
            users.put("admin@gmail.com", new String[]{"a123", "admin"});
            users.put("doctor@gmail.com", new String[]{"d123", "doctor"});
            users.put("nurse@gmail.com", new String[]{"n123", "nurse"});
            users.put("pharmacy@gmail.com", new String[]{"p123", "pharmacy"});
        }

        @Override
        protected boolean check(String username, String password) {
            if (!users.containsKey(username)) {
                JOptionPane.showMessageDialog(null, "User not found!");
                return false;
            }

            String[] data = users.get(username);
            if (!data[0].equals(password)) {
                JOptionPane.showMessageDialog(null, "Invalid password!");
                return false;
            }

            String role = data[1];
            JOptionPane.showMessageDialog(null, "Login Successful! Role: " + role.toUpperCase());

            // Load dashboard based on role
            switch (role) {
                case "admin":
                    new adminDashboard().setVisible(true);
                    break;
                case "doctor":
                    new doctorDashboard().setVisible(true);
                    break;
                case "nurse":
                    new nurseDashboard().setVisible(true);
                    break;
                case "pharmacy":
                    new pharmacyDashboard().setVisible(true);
                    break;
            }
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("GLOBEMED HOSPITAL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 230, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 230, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setText(" LOGIN  ");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/oo.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password = String.valueOf(jPasswordField1.getPassword());

        // Build the chain
        AuthHandler usernameHandler = new UsernameHandler();
        AuthHandler passwordHandler = new PasswordHandler();
        AuthHandler credentialHandler = new CredentialHandler();

        usernameHandler.setNext(passwordHandler).setNext(credentialHandler);

        // Run the chain
        usernameHandler.handle(username, password);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatCyanLightIJTheme.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
